# Generated by Django 2.1.5 on 2019-01-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storefront',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='storefront',
            name='storefront_itemcode',
        ),
        migrations.AddField(
            model_name='event',
            name='storefront_itemcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='storefront',
            table='hz_evetns_store_front',
        ),
    ]
