# Generated by Django 2.1.5 on 2019-01-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190128_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='contact_email',
            field=models.EmailField(max_length=255),
        ),
    ]
