# Generated by Django 2.1.5 on 2019-01-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190128_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='guests',
            field=models.IntegerField(default=0),
        ),
    ]
