# Generated by Django 2.1.5 on 2019-01-29 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20190129_0816'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attendee',
            table='hz_events_attendee',
        ),
        migrations.AlterModelTable(
            name='event',
            table='hz_events_event',
        ),
        migrations.AlterModelTable(
            name='eventform',
            table='hz_events_event_form',
        ),
        migrations.AlterModelTable(
            name='storefront',
            table='hz_events_store_front',
        ),
    ]
