# Generated by Django 2.1.5 on 2019-01-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20190129_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventform',
            name='form_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
