# Generated by Django 2.1.5 on 2019-02-07 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20190129_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='guests_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_form',
            field=models.ForeignKey(limit_choices_to={'active': True, 'trash': False}, on_delete=django.db.models.deletion.PROTECT, to='events.EventForm'),
        ),
        migrations.AlterField(
            model_name='event',
            name='storefront',
            field=models.ForeignKey(blank=True, limit_choices_to={'active': True, 'trash': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.StoreFront'),
        ),
    ]
