# Generated by Django 2.1.5 on 2019-02-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_max_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allowed_guest',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=0),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='guests',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], default=0),
        ),
    ]
