# Generated by Django 2.1.5 on 2019-02-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20190213_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='guests',
            field=models.IntegerField(choices=[(0, '0')], default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(max_length=12),
        ),
    ]
