# Generated by Django 2.1.5 on 2019-02-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20190218_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='confirmation_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
