# Generated by Django 2.1.5 on 2019-02-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20190221_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contact_name',
            field=models.CharField(default='ed', max_length=75),
            preserve_default=False,
        ),
    ]
