# Generated by Django 2.1.5 on 2019-02-21 20:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20190221_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='refund_policy',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
