# Generated by Django 2.1.5 on 2019-02-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_event_refund_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='institute',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
