# Generated by Django 2.1.5 on 2019-02-22 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_attendee_institute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendee',
            old_name='institute',
            new_name='institution',
        ),
    ]
