# Generated by Django 2.1.5 on 2019-02-25 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20190222_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventform',
            name='form_image',
        ),
    ]
