# Generated by Django 2.1.5 on 2019-02-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_remove_eventform_form_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location_address',
            field=models.CharField(default='w', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='location_map_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location_name',
            field=models.CharField(default='w', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendee',
            name='guests',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=0),
        ),
    ]
