# Generated by Django 2.1.5 on 2019-03-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_auto_20190227_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='registration_type',
            field=models.CharField(default='other', max_length=30),
        ),
    ]
