# Generated by Django 2.1.5 on 2019-03-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_auto_20190320_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='affiliation',
            field=models.CharField(choices=[('College of Engineering', 'College of Engineering'), ('College of Fine Arts', 'College of Fine Arts'), ('Dietrich College of Humanities & Social Sciences', 'Dietrich College of Humanities & Social Sciences'), ('Heinz College of Information Systems and Public Policy', 'Heinz College of Information Systems and Public Policy'), ('Mellon College of Science', 'Mellon College of Science'), ('School of Computer Science', 'School of Computer Science'), ('Tepper School of Business', 'Tepper School of Business'), ('Other', 'Other')], default='Other', max_length=150),
        ),
    ]
