# Generated by Django 2.1.5 on 2019-03-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_auto_20190320_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='item_code',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
