# Generated by Django 2.1.5 on 2019-03-20 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_attendee_item_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendee',
            old_name='item_code',
            new_name='itemcode',
        ),
    ]
