# Generated by Django 2.1.5 on 2019-03-20 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_auto_20190320_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='itemcode',
        ),
    ]
