# Generated by Django 2.1.5 on 2019-04-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_remove_attendee_itemcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='signup_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
