# Generated by Django 2.1.5 on 2019-04-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_auto_20190401_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='guests_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Guest Name(s)'),
        ),
        migrations.AlterField(
            model_name='managementgroup',
            name='members',
            field=models.TextField(),
        ),
    ]
