# Generated by Django 2.2 on 2019-04-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0037_event_show_registration_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='guests_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Guest Name(s)'),
        ),
    ]
