# Generated by Django 2.2 on 2019-04-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0038_auto_20190409_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='show_form_only',
            field=models.BooleanField(default=False),
        ),
    ]
