# Generated by Django 2.2 on 2019-04-16 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0039_event_show_form_only'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendee',
            old_name='institution',
            new_name='organization',
        ),
    ]
