# Generated by Django 2.2 on 2019-04-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0040_auto_20190416_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
