# Generated by Django 2.1.8 on 2019-04-25 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0042_attendee_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_-]+$', 'Only alphanumeric, dash, and underscore characters are allowed.')]),
        ),
    ]
