"""
Django settings for heinz_signup project.

Generated by 'django-admin startproject' using Django 2.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os, socket

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_URL = 'http://event.heinz.cmu.edu/'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!hi2(^s9s4ih$d(q_ow)h&#bykc*u#*4qo=56lb!ed1w*-_e@n'

# set the production or development settings
if socket.gethostname().startswith('heinz-notwas'):
    DJANGO_HOST = 'prod'
else:
    # assume development
    DJANGO_HOST = 'dev'


# use settings specific to environment
if DJANGO_HOST == 'prod':

    # SECURITY WARNING: don't run with debug turned on in production!
    DEBUG = False
    ALLOWED_HOSTS = [
        'event.heinz.cmu.edu',
    ]
    HOSTNAME = 'event.heinz.cmu.edu'
else:

    # SECURITY WARNING: don't run with debug turned on in production!
    DEBUG = True
    ALLOWED_HOSTS = [
        '127.0.0.1',
        'event.heinz.cmu.edu',
    ]

INSTALLED_APPS = [
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        'crispy_forms',
        'ckeditor',
        'additional_widgets',
        'events.apps.EventsConfig',
        'event_management.apps.EventManagementConfig'
    ]

# Enable the shibboleth application
if DJANGO_HOST == 'prod':
    INSTALLED_APPS += [
        'shibboleth',
    ]

MIDDLEWARE = [
        'django.middleware.security.SecurityMiddleware',
        'django.contrib.sessions.middleware.SessionMiddleware',
        'django.middleware.common.CommonMiddleware',
        'django.middleware.csrf.CsrfViewMiddleware',
        'django.contrib.auth.middleware.AuthenticationMiddleware',
        'django.contrib.messages.middleware.MessageMiddleware',
        'django.middleware.clickjacking.XFrameOptionsMiddleware',
    ]

#LOGIN_REDIRECT_URL = '/manage'

if DJANGO_HOST == 'prod':
    AUTHENTICATION_BACKENDS = (
        'shibboleth.backends.ShibbolethRemoteUserBackend',
    )

    MIDDLEWARE += [
        'shibboleth.middleware.ShibbolethRemoteUserMiddleware',
    ]

    SHIBBOLETH_ATTRIBUTE_MAP = {
        "eppn": (True, "username"),
    }

    LOGIN_URL = 'https://event.heinz.cmu.edu/Shibboleth.sso/Login'
    SHIBBOLETH_GROUP_ATTRIBUTES = ['affiliation', ]
    REDIRECT_FIELD_NAME = 'target'


ROOT_URLCONF = 'heinz_signup.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 'shibboleth.context_processors.login_link',
                # 'shibboleth.context_processors.logout_link',
                'heinz_signup.context_processor.extra_context',
            ],
        },
    },
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'

WSGI_APPLICATION = 'heinz_signup.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    # }
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'heinz_signup',
        'USER': 'heinz_signup_usr',
        'PASSWORD': 'Nuf$5oiRh1Ou#j',
        'HOST': 'localhost',
        'PORT': '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_L10N = False

USE_TZ = True

TIME_INPUT_FORMATS = ['%I:%M %p']
# TIME_FORMAT = 'I:M p'
DATE_INPUT_FORMATS = ['%m/%d/%Y']
DATE_FORMAT = 'm/d/Y'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

MEDIA_ROOT = (os.path.join('media'))
MEDIA_URL = '/media/'

STATIC_URL = '/static/'
#STATIC_ROOT = BASE_DIR + '/static'
STATICFILES_DIRS = (os.path.join('static'), )

CKEDITOR_CONFIGS = {
    'default': {
        'skin': 'moono',
        'height': 300,
        'width': 700,
        'toolbar_eventconfig': [
            {'name': 'basicstyles',
             'items': ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']},
            {'name': 'paragraph',
             'items': ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-',
                       'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl',
                       'Language']},
            {'name': 'links', 'items': ['Link', 'Unlink', 'Anchor']},
            {'name': 'styles', 'items': ['Styles', 'Format', 'Font', 'FontSize']},
            # {'name': 'colors', 'items': ['TextColor', 'BGColor']},
            {'name': 'tools', 'items': ['Maximize', 'ShowBlocks']},
        ],
        'toolbar': 'eventconfig',
    },
}

EMAIL_HOST = 'relay.andrew.cmu.edu'
EMAIL_PORT = 25
